so $HOME/.vim/config/nerdtree.vim
so $HOME/.vim/config/ultisnips.vim
so $HOME/.vim/config/nerdcommenter.vim
so $HOME/.vim/config/deoplete.vim
so $HOME/.vim/config/fzf.vim
so $HOME/.vim/config/neomake.vim
so $HOME/.vim/config/airline.vim
so $HOME/.vim/config/tagbar.vim
so $HOME/.vim/config/tmux.vim
so $HOME/.vim/config/multiple-cursor.vim
so $HOME/.vim/config/markdown.vim
so $HOME/.vim/config/go.vim
so $HOME/.vim/config/js.vim
